/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FriendInviteeResponseRelationshipStatus } from './friendInviteeResponseRelationshipStatus';

export interface FriendInviteeResponse {
  userId?: number;
  displayName?: string;
  profileImageUrl?: string;
  relationshipStatus?: FriendInviteeResponseRelationshipStatus;
  requestId?: number;
  daysSinceStart?: number;
  targetSuccessCount?: number;
}
