/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FriendUserResponse } from './friendUserResponse';

export interface FriendRequestResponse {
  requestId?: number;
  user?: FriendUserResponse;
  createdAt?: string;
}
