/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FriendRelationshipStatus } from './friendRelationshipStatus';

export interface FriendListUserResponse {
  userId?: number;
  displayName?: string;
  profileImageUrl?: string;
  relationshipStatus?: FriendRelationshipStatus;
  requestId?: number;
  /**
   * @minLength 5
   * @maxLength 5
   */
  userCode: string;
}
