/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FriendListUserResponse } from './friendListUserResponse';

export interface FriendReceivedRequestResponse {
  requestId: number;
  user: FriendListUserResponse;
  createdAt: string;
}
