/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type FriendRelationshipStatus =
  (typeof FriendRelationshipStatus)[keyof typeof FriendRelationshipStatus];

export const FriendRelationshipStatus = {
  NONE: 'NONE',
  SELF: 'SELF',
  PENDING_SENT: 'PENDING_SENT',
  PENDING_RECEIVED: 'PENDING_RECEIVED',
  FRIEND: 'FRIEND',
} as const;
