/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateFriendRequest,
  FriendInviteResponse,
  FriendInviteeResponse,
  FriendReceivedRequestResponse,
  FriendRequestResponse,
  FriendResponse,
  FriendSearchResponse,
  SearchByEmailParams,
} from './model';

import { friendAxios } from '../friendMutator';
import type { ErrorType } from '../friendMutator';
export const sendRequest = (createFriendRequest: CreateFriendRequest, signal?: AbortSignal) => {
  return friendAxios<FriendRequestResponse>({
    url: `/friends/requests`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createFriendRequest,
    signal,
  });
};

export const getSendRequestMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendRequest>>,
    TError,
    { data: CreateFriendRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendRequest>>,
  TError,
  { data: CreateFriendRequest },
  TContext
> => {
  const mutationKey = ['sendRequest'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendRequest>>,
    { data: CreateFriendRequest }
  > = (props) => {
    const { data } = props ?? {};

    return sendRequest(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendRequestMutationResult = NonNullable<Awaited<ReturnType<typeof sendRequest>>>;
export type SendRequestMutationBody = CreateFriendRequest;
export type SendRequestMutationError = ErrorType<unknown>;

export const useSendRequest = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sendRequest>>,
      TError,
      { data: CreateFriendRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sendRequest>>,
  TError,
  { data: CreateFriendRequest },
  TContext
> => {
  return useMutation(getSendRequestMutationOptions(options), queryClient);
};

export const acceptRequest = (requestId: number, signal?: AbortSignal) => {
  return friendAxios<FriendResponse>({
    url: `/friends/requests/${requestId}/accept`,
    method: 'POST',
    signal,
  });
};

export const getAcceptRequestMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptRequest>>,
    TError,
    { requestId: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptRequest>>,
  TError,
  { requestId: number },
  TContext
> => {
  const mutationKey = ['acceptRequest'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptRequest>>,
    { requestId: number }
  > = (props) => {
    const { requestId } = props ?? {};

    return acceptRequest(requestId);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptRequestMutationResult = NonNullable<Awaited<ReturnType<typeof acceptRequest>>>;

export type AcceptRequestMutationError = ErrorType<unknown>;

export const useAcceptRequest = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptRequest>>,
      TError,
      { requestId: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof acceptRequest>>,
  TError,
  { requestId: number },
  TContext
> => {
  return useMutation(getAcceptRequestMutationOptions(options), queryClient);
};

export const getFriends = (signal?: AbortSignal) => {
  return friendAxios<FriendResponse[]>({ url: `/friends`, method: 'GET', signal });
};

export const getGetFriendsQueryKey = () => {
  return ['friends'] as const;
};

export const getGetFriendsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFriendsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFriends>>> = ({ signal }) =>
    getFriends(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFriends>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFriendsQueryResult = NonNullable<Awaited<ReturnType<typeof getFriends>>>;
export type GetFriendsQueryError = ErrorType<unknown>;

export function useGetFriends<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFriends>>,
          TError,
          Awaited<ReturnType<typeof getFriends>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFriends<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFriends>>,
          TError,
          Awaited<ReturnType<typeof getFriends>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFriends<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetFriends<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFriendsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetFriendsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFriendsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFriends>>> = ({ signal }) =>
    getFriends(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getFriends>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFriendsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getFriends>>>;
export type GetFriendsSuspenseQueryError = ErrorType<unknown>;

export function useGetFriendsSuspense<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFriendsSuspense<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFriendsSuspense<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetFriendsSuspense<
  TData = Awaited<ReturnType<typeof getFriends>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFriends>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFriendsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const searchByEmail = (params: SearchByEmailParams, signal?: AbortSignal) => {
  return friendAxios<FriendSearchResponse>({
    url: `/friends/search`,
    method: 'GET',
    params,
    signal,
  });
};

export const getSearchByEmailQueryKey = (params?: SearchByEmailParams) => {
  return ['friends', 'search', ...(params ? [params] : [])] as const;
};

export const getSearchByEmailQueryOptions = <
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchByEmailQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchByEmail>>> = ({ signal }) =>
    searchByEmail(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchByEmail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchByEmailQueryResult = NonNullable<Awaited<ReturnType<typeof searchByEmail>>>;
export type SearchByEmailQueryError = ErrorType<unknown>;

export function useSearchByEmail<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByEmail>>,
          TError,
          Awaited<ReturnType<typeof searchByEmail>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchByEmail<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByEmail>>,
          TError,
          Awaited<ReturnType<typeof searchByEmail>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchByEmail<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSearchByEmail<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchByEmailQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getSearchByEmailSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchByEmailQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchByEmail>>> = ({ signal }) =>
    searchByEmail(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof searchByEmail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchByEmailSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchByEmail>>
>;
export type SearchByEmailSuspenseQueryError = ErrorType<unknown>;

export function useSearchByEmailSuspense<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchByEmailSuspense<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchByEmailSuspense<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSearchByEmailSuspense<
  TData = Awaited<ReturnType<typeof searchByEmail>>,
  TError = ErrorType<unknown>,
>(
  params: SearchByEmailParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchByEmail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchByEmailSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getSentRequests = (signal?: AbortSignal) => {
  return friendAxios<FriendRequestResponse[]>({
    url: `/friends/requests/sent`,
    method: 'GET',
    signal,
  });
};

export const getGetSentRequestsQueryKey = () => {
  return ['friends', 'requests', 'sent'] as const;
};

export const getGetSentRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSentRequestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSentRequests>>> = ({ signal }) =>
    getSentRequests(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSentRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSentRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getSentRequests>>>;
export type GetSentRequestsQueryError = ErrorType<unknown>;

export function useGetSentRequests<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSentRequests>>,
          TError,
          Awaited<ReturnType<typeof getSentRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSentRequests<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSentRequests>>,
          TError,
          Awaited<ReturnType<typeof getSentRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSentRequests<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSentRequests<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSentRequestsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetSentRequestsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSentRequestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSentRequests>>> = ({ signal }) =>
    getSentRequests(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getSentRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSentRequestsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSentRequests>>
>;
export type GetSentRequestsSuspenseQueryError = ErrorType<unknown>;

export function useGetSentRequestsSuspense<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSentRequestsSuspense<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSentRequestsSuspense<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSentRequestsSuspense<
  TData = Awaited<ReturnType<typeof getSentRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSentRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSentRequestsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getReceivedRequests = (signal?: AbortSignal) => {
  return friendAxios<FriendReceivedRequestResponse[]>({
    url: `/friends/requests/received`,
    method: 'GET',
    signal,
  });
};

export const getGetReceivedRequestsQueryKey = () => {
  return ['friends', 'requests', 'received'] as const;
};

export const getGetReceivedRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReceivedRequestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReceivedRequests>>> = ({ signal }) =>
    getReceivedRequests(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReceivedRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReceivedRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReceivedRequests>>
>;
export type GetReceivedRequestsQueryError = ErrorType<unknown>;

export function useGetReceivedRequests<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceivedRequests>>,
          TError,
          Awaited<ReturnType<typeof getReceivedRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReceivedRequests<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceivedRequests>>,
          TError,
          Awaited<ReturnType<typeof getReceivedRequests>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReceivedRequests<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetReceivedRequests<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetReceivedRequestsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetReceivedRequestsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReceivedRequestsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReceivedRequests>>> = ({ signal }) =>
    getReceivedRequests(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getReceivedRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReceivedRequestsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReceivedRequests>>
>;
export type GetReceivedRequestsSuspenseQueryError = ErrorType<unknown>;

export function useGetReceivedRequestsSuspense<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReceivedRequestsSuspense<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReceivedRequestsSuspense<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetReceivedRequestsSuspense<
  TData = Awaited<ReturnType<typeof getReceivedRequests>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getReceivedRequests>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetReceivedRequestsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getMyInvite = (signal?: AbortSignal) => {
  return friendAxios<FriendInviteResponse>({ url: `/friends/invite`, method: 'GET', signal });
};

export const getGetMyInviteQueryKey = () => {
  return ['friends', 'invite'] as const;
};

export const getGetMyInviteQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyInviteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInvite>>> = ({ signal }) =>
    getMyInvite(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyInvite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyInviteQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInvite>>>;
export type GetMyInviteQueryError = ErrorType<unknown>;

export function useGetMyInvite<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInvite>>,
          TError,
          Awaited<ReturnType<typeof getMyInvite>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyInvite<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInvite>>,
          TError,
          Awaited<ReturnType<typeof getMyInvite>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyInvite<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyInvite<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyInviteQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetMyInviteSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyInviteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInvite>>> = ({ signal }) =>
    getMyInvite(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMyInvite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyInviteSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInvite>>>;
export type GetMyInviteSuspenseQueryError = ErrorType<unknown>;

export function useGetMyInviteSuspense<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyInviteSuspense<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyInviteSuspense<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyInviteSuspense<
  TData = Awaited<ReturnType<typeof getMyInvite>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyInvite>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyInviteSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getInvitee = (code: string, signal?: AbortSignal) => {
  return friendAxios<FriendInviteeResponse>({
    url: `/friends/invite/${code}`,
    method: 'GET',
    signal,
  });
};

export const getGetInviteeQueryKey = (code: string) => {
  return ['friends', 'invite', code] as const;
};

export const getGetInviteeQueryOptions = <
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInviteeQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvitee>>> = ({ signal }) =>
    getInvitee(code, signal);

  return { queryKey, queryFn, enabled: !!code, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getInvitee>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetInviteeQueryResult = NonNullable<Awaited<ReturnType<typeof getInvitee>>>;
export type GetInviteeQueryError = ErrorType<unknown>;

export function useGetInvitee<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitee>>,
          TError,
          Awaited<ReturnType<typeof getInvitee>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInvitee<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitee>>,
          TError,
          Awaited<ReturnType<typeof getInvitee>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInvitee<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetInvitee<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetInviteeQueryOptions(code, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetInviteeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInviteeQueryKey(code);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvitee>>> = ({ signal }) =>
    getInvitee(code, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getInvitee>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetInviteeSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getInvitee>>>;
export type GetInviteeSuspenseQueryError = ErrorType<unknown>;

export function useGetInviteeSuspense<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInviteeSuspense<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetInviteeSuspense<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetInviteeSuspense<
  TData = Awaited<ReturnType<typeof getInvitee>>,
  TError = ErrorType<unknown>,
>(
  code: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getInvitee>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetInviteeSuspenseQueryOptions(code, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const unfriend = (friendshipId: number, signal?: AbortSignal) => {
  return friendAxios<void>({ url: `/friends/${friendshipId}`, method: 'DELETE', signal });
};

export const getUnfriendMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unfriend>>,
    TError,
    { friendshipId: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unfriend>>,
  TError,
  { friendshipId: number },
  TContext
> => {
  const mutationKey = ['unfriend'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unfriend>>,
    { friendshipId: number }
  > = (props) => {
    const { friendshipId } = props ?? {};

    return unfriend(friendshipId);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnfriendMutationResult = NonNullable<Awaited<ReturnType<typeof unfriend>>>;

export type UnfriendMutationError = ErrorType<unknown>;

export const useUnfriend = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unfriend>>,
      TError,
      { friendshipId: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof unfriend>>,
  TError,
  { friendshipId: number },
  TContext
> => {
  return useMutation(getUnfriendMutationOptions(options), queryClient);
};

export const deletePendingRequest = (requestId: number, signal?: AbortSignal) => {
  return friendAxios<void>({ url: `/friends/requests/${requestId}`, method: 'DELETE', signal });
};

export const getDeletePendingRequestMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePendingRequest>>,
    TError,
    { requestId: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePendingRequest>>,
  TError,
  { requestId: number },
  TContext
> => {
  const mutationKey = ['deletePendingRequest'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePendingRequest>>,
    { requestId: number }
  > = (props) => {
    const { requestId } = props ?? {};

    return deletePendingRequest(requestId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePendingRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePendingRequest>>
>;

export type DeletePendingRequestMutationError = ErrorType<unknown>;

export const useDeletePendingRequest = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePendingRequest>>,
      TError,
      { requestId: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deletePendingRequest>>,
  TError,
  { requestId: number },
  TContext
> => {
  return useMutation(getDeletePendingRequestMutationOptions(options), queryClient);
};
